In [10]:
from numpy import array

In [11]:
l = [1.0,2.0,3.0]

In [12]:
a = array(l)

In [13]:
print(a)

[1. 2. 3.]


In [14]:
print(a.shape)

(3,)


In [15]:
print(a.dtype)

float64


In [16]:
from numpy import empty

In [17]:
a = empty([3,3])

In [18]:
print(a)

[[0.00e+000 0.00e+000 0.00e+000]
 [0.00e+000 0.00e+000 7.49e-321]
 [0.00e+000 0.00e+000 0.00e+000]]


In [19]:
from numpy import zeros

In [20]:
a = zeros([3,5])

In [21]:
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
from numpy import ones

In [23]:
a =  ones([5])

In [24]:
print(a)

[1. 1. 1. 1. 1.]


In [25]:
from numpy import vstack

In [26]:
a1= array([1,2,3])

In [27]:
a2 = array([4,5,6])

In [28]:
a3 = vstack((a1,a2))

In [29]:
print(a3)

[[1 2 3]
 [4 5 6]]


In [30]:
print(a3.shape)

(2, 3)


In [31]:
from numpy import hstack

In [32]:
a3 = hstack((a1,a2))

In [33]:
print(a3)

[1 2 3 4 5 6]


In [34]:
print(a3.shape)

(6,)
