In [1]:
from numpy import array

In [2]:
A = array([1,2,3])

In [3]:
B = array([2,3,4])

In [4]:
C = A+B

In [5]:
C

array([3, 5, 7])

In [6]:
C = B-A

In [7]:
C

array([1, 1, 1])

In [8]:
C = A*B

In [9]:
C

array([ 2,  6, 12])

In [12]:
C = B/A

In [13]:
C

array([2.        , 1.5       , 1.33333333])

In [14]:
C = A.dot(B)

In [15]:
C

20

In [16]:
scaler = 0.5

In [17]:
C = scaler*A

In [18]:
C

array([0.5, 1. , 1.5])