In [1]:
from numpy import array

In [2]:
A = array([[1,2,3],[4,5,6]])

In [3]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
B = array([[1,2,3],[4,5,6]])

In [5]:
B

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
C = A + B

In [7]:
C

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [8]:
C = A - B

In [9]:
C

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
C = A * B

In [11]:
C

array([[ 1,  4,  9],
       [16, 25, 36]])

In [12]:
C = A/B

In [13]:
C

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
A = array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
B = array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
C = A.dot(B)

In [17]:
C

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [18]:
D = A@B

In [19]:
D

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

Matrix Vector Multiplication

In [21]:
A = array([[1,2],[4,5],[7,8]])

In [22]:
B = array([0.5,0.5])

In [23]:
C = A.dot(B)

In [24]:
C

array([1.5, 4.5, 7.5])

Matrix Scaler Multiplication

In [25]:
B = 0.5

In [26]:
C = A.dot(B)

In [27]:
C

array([[0.5, 1. ],
       [2. , 2.5],
       [3.5, 4. ]])