In [2]:
from numpy import array
from numpy import triu
from numpy import tril

In [4]:
A = array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
lower = tril(A)

In [7]:
print(lower)

[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [8]:
upper = triu(A)

In [9]:
upper

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [10]:
from numpy import diag

In [11]:
A = array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
d = diag(A)

In [13]:
d

array([1, 5, 9])

In [14]:
D = diag(d)

In [15]:
D

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [16]:
from numpy import identity

In [17]:
I = identity(3)

In [18]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
from numpy.linalg import inv

In [21]:
Q = array([[1,0],[0,-1]])

In [23]:
print(Q)

[[ 1  0]
 [ 0 -1]]


In [24]:
print(Q.T)

[[ 1  0]
 [ 0 -1]]
