Transpose of a matrix

In [17]:
from numpy import array

In [18]:
A = array([[1,2,],[3,4],[5,6]])

In [19]:
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [20]:
print(A.T)

[[1 3 5]
 [2 4 6]]


Inverse of a Matrix

In [21]:
import numpy.linalg as inv

In [22]:
A = array([[1.0,2.0],[3.0,4.0]])

In [23]:
print(A)

[[1. 2.]
 [3. 4.]]


In [24]:
B = inv(A)

TypeError: 'module' object is not callable