Transpose of a matrix

In [1]:
from numpy import array

In [2]:
A = array([[1,2,],[3,4],[5,6]])

In [3]:
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
print(A.T)

[[1 3 5]
 [2 4 6]]


Inverse of a Matrix

In [5]:
import numpy.linalg as inv

In [6]:
A = array([[1.0,2.0],[3.0,4.0]])

In [7]:
print(A)

[[1. 2.]
 [3. 4.]]


In [8]:
B = inv(A)

TypeError: 'module' object is not callable

In [10]:
C = A.dot(B)

NameError: name 'B' is not defined

In [11]:
from numpy import trace

In [12]:
A = array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
B = trace(A)

In [15]:
print(B)

15


In [16]:
from numpy.linalg import det

In [18]:
A = array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
B = det(A)

In [22]:
print(B)

0.0


In [23]:
from numpy.linalg import matrix_rank

In [24]:
A = array([1,2,3])

In [25]:
B = matrix_rank(A)

In [26]:
print(B)

1


In [27]:
C = array([0,0,0,0,0])

In [28]:
D = matrix_rank(C)

In [29]:
print(D)

0


In [30]:
E = array([[0,0], [0,0]])

In [31]:
print(matrix_rank(E))

0


In [32]:
print(matrix_rank(array([[1,2],[1,2]])))

1


In [33]:
print(matrix_rank(array([[1,2],[3,4]])))

2
