In [4]:
from numpy import array
from scipy.sparse import csr_matrix

In [5]:
A = array([[1,2,0,0,0,0],
          [9,4,0,0,0,0],
          [0,0,0,2,3,0]])

In [6]:
print(A)

[[1 2 0 0 0 0]
 [9 4 0 0 0 0]
 [0 0 0 2 3 0]]


In [7]:
s = csr_matrix(A)

In [9]:
print(s)

  (0, 0)	1
  (0, 1)	2
  (1, 0)	9
  (1, 1)	4
  (2, 3)	2
  (2, 4)	3


In [10]:
B = s.todense()

In [11]:
B

matrix([[1, 2, 0, 0, 0, 0],
        [9, 4, 0, 0, 0, 0],
        [0, 0, 0, 2, 3, 0]], dtype=int32)