In [1]:
# tensor addition 

In [2]:
from numpy import array 

In [3]:
# define first tensor 

In [5]:
A = array([ [[1,2,3], [4,5,6], [7,8,9]], [[11,12,13], [14,15,16], [17,18,19]], [[21,22,23], [24,25,26], [27,28,29]]]) 

In [6]:
# define second tensor

In [7]:
 B = array([ [[1,2,3], [4,5,6], [7,8,9]], [[11,12,13], [14,15,16], [17,18,19]], [[21,22,23], [24,25,26], [27,28,29]]]) 

In [8]:
# add tensors 

In [10]:
C = A + B 

In [11]:
print(C)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


In [12]:
C = A - B

In [13]:
C

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [14]:
C = A * B

In [15]:
C

array([[[  1,   4,   9],
        [ 16,  25,  36],
        [ 49,  64,  81]],

       [[121, 144, 169],
        [196, 225, 256],
        [289, 324, 361]],

       [[441, 484, 529],
        [576, 625, 676],
        [729, 784, 841]]])

In [16]:
C = A/B

In [17]:
C

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [18]:
from numpy import tensordot

In [19]:
A = array([2,3])

In [20]:
B = array([4,5])

In [21]:
C = tensordot(A,B, axes=0)

In [22]:
C

array([[ 8, 10],
       [12, 15]])