In [20]:
from numpy import array
from scipy.linalg import svd

In [21]:
A = array([[1,2],
           [3,4],
           [5,6]])

In [22]:
U, s, V = svd(A)

In [23]:
print(U)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]


In [24]:
print(s)

[9.52551809 0.51430058]


In [25]:
print(V)

[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [26]:
## Reconstruct matrix

In [27]:
from numpy import diag
from numpy import zeros

In [28]:
Sigma = zeros((A.shape[0], A.shape[1]))

In [29]:
Sigma[:A.shape[1],:A.shape[1]] = diag(s)

In [30]:
B = U.dot(Sigma).dot(V)

In [31]:
print(B)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [32]:
# For sqaure matrix

In [33]:
A = array([[1,2,3],
           [4,5,6],
           [7,8,9]])

In [34]:
U, s, V = svd(A)

In [35]:
Sigma = diag(s)

In [36]:
B = U.dot(Sigma).dot(V)

In [37]:
print(B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
