In [4]:
#also known as  Moore-Penrose Inverse
# for calculating inverse of rectangular matrix

In [5]:
from numpy import array
from numpy.linalg import pinv

In [6]:
A = array([[0.2, 0.4],
           [0.5, 0.6],
           [0.7, 0.8],
           [0.9, 0.3]])

In [7]:
print(A)

[[0.2 0.4]
 [0.5 0.6]
 [0.7 0.8]
 [0.9 0.3]]


In [8]:
B = pinv(A)

In [9]:
print(B)

[[-0.44707681 -0.19296905 -0.17768437  1.45586549]
 [ 0.75277035  0.66679404  0.81199847 -1.1692778 ]]


In [10]:
# Calculating pinv manually via SVD

In [11]:
from numpy.linalg import svd
from numpy import diag
from numpy import zeros

In [12]:
A = array([[0.2, 0.4],
           [0.5, 0.6],
           [0.7, 0.8],
           [0.9, 0.3]])

In [13]:
print(A)

[[0.2 0.4]
 [0.5 0.6]
 [0.7 0.8]
 [0.9 0.3]]


In [14]:
U, s, V = svd(A)

In [15]:
print(U)

[[-0.25432049 -0.38342387 -0.56255392 -0.68690633]
 [-0.47434416 -0.28033822 -0.45147005  0.7018425 ]
 [-0.64793611 -0.32465136  0.67615588 -0.13264054]
 [-0.5389782   0.81792305 -0.15007034 -0.13410178]]


In [17]:
print(s)

[1.62538727 0.44510247]


In [18]:
print(V)

[[-0.75469512 -0.65607567]
 [ 0.65607567 -0.75469512]]


In [19]:
d = 1.0/s

In [20]:
print(d)

[0.61523799 2.24667367]


In [21]:
D = zeros(A.shape)

In [23]:
D[:A.shape[1], :A.shape[1]] = diag(d)

In [25]:
B = V.T.dot(D.T).dot(U.T)

In [26]:
print(B)

[[-0.44707681 -0.19296905 -0.17768437  1.45586549]
 [ 0.75277035  0.66679404  0.81199847 -1.1692778 ]]
