In [1]:
from numpy import array
from numpy import zeros
from numpy import diag
from scipy.linalg import svd

In [2]:
A = array([ [1,2,3,4,5,6,7,8,9,10], [11,12,13,14,15,16,17,18,19,20], [21,22,23,24,25,26,27,28,29,30]])

In [3]:
U, s, V = svd(A)

In [4]:
print(U)

[[-0.19101157  0.89266338  0.40824829]
 [-0.51371859  0.26348917 -0.81649658]
 [-0.8364256  -0.36568503  0.40824829]]


In [5]:
print(s)

[9.69657342e+01 7.25578339e+00 5.43064394e-15]


In [6]:
print(V)

[[-0.24139304 -0.25728686 -0.27318068 -0.2890745  -0.30496832 -0.32086214
  -0.33675595 -0.35264977 -0.36854359 -0.38443741]
 [-0.53589546 -0.42695236 -0.31800926 -0.20906617 -0.10012307  0.00882003
   0.11776313  0.22670623  0.33564933  0.44459242]
 [-0.71590327  0.22125777  0.35844894  0.23137425  0.12099174  0.27768425
  -0.35015608  0.05691924 -0.00338669 -0.19723014]
 [-0.03274747 -0.17891449 -0.37608172  0.89207072 -0.08211107 -0.11995167
   0.02920549 -0.06831525 -0.05443306 -0.00872147]
 [-0.07588946 -0.05763181 -0.30552732 -0.08865234  0.92223855 -0.12098055
  -0.00525156 -0.09919877 -0.09845351 -0.07065325]
 [ 0.06629874  0.08438747 -0.47449715 -0.0967393  -0.08248279  0.8362855
   0.03555043 -0.13520148 -0.138849   -0.09475243]
 [-0.33592049  0.16549299  0.06013546 -0.02444478 -0.06055817 -0.0839398
   0.85527901 -0.15616659 -0.18989278 -0.22998484]
 [-0.01998524  0.32695283 -0.33338835 -0.05818541 -0.07378355 -0.16577225
  -0.03336365  0.80303148 -0.22688989 -0.21861597]
 [

In [9]:
Sigma = zeros((A.shape[0], A.shape[1]))

In [11]:
Sigma[:A.shape[0], :A.shape[0]] = diag(s)

In [12]:
n_elements = 2

In [14]:
Sigma = Sigma[:, :n_elements]

In [15]:
V = V[:n_elements, :]

In [16]:
B = U.dot(Sigma).dot(V)

In [18]:
print(B)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]


In [19]:
T = U.dot(Sigma)

In [20]:
print(T)

[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


In [21]:
T = A.dot(V.T)

In [22]:
print(T)

[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


In [23]:
# This can be done directly by TruncatedSVD class in sklearn, let's see how

In [24]:
from sklearn.decomposition import TruncatedSVD

In [25]:
A = array([ [1,2,3,4,5,6,7,8,9,10], [11,12,13,14,15,16,17,18,19,20], [21,22,23,24,25,26,27,28,29,30]])

In [26]:
svd = TruncatedSVD(n_components=2)

In [27]:
svd.fit(A)

TruncatedSVD(algorithm='randomized', n_components=2, n_iter=5,
             random_state=None, tol=0.0)

In [28]:
result = svd.transform(A)

In [29]:
print(result)

[[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]
