This tutorial is divided into 4 parts; they are:
1. Expected Value and Mean
2. Variance and Standard Deviation
3. Covariance and Correlation
4. Covariance Matrix

In [10]:
from numpy import array
from numpy import mean

In [11]:
v = array([1,2,3,4,5,6])

In [12]:
print(v)

[1 2 3 4 5 6]


In [13]:
res = mean(v)

In [14]:
print(res)

3.5


In [15]:
# Row wise and column wise mean

In [16]:
v = array([[1,2,3,4,5,6],
           [1,2,3,4,5,6]])

In [17]:
mean_col = mean(v, axis = 0)

In [18]:
print(mean_col)

[1. 2. 3. 4. 5. 6.]


In [19]:
mean_row = mean(v, axis = 1)

In [20]:
print(mean_row)

[3.5 3.5]


In [39]:
# variance

In [22]:
from numpy import var

In [23]:
A = array([1,2,3,4,5,6])

In [30]:
variance = var(A, ddof=1)

In [31]:
print(variance)

3.5


In [32]:
# Variance row and column wise

In [33]:
A = array([[1,2,3,4,5,6],
           [1,2,3,4,5,6]])

In [34]:
var_col = var(A, ddof=1, axis = 0)

In [35]:
print(var_col)

[0. 0. 0. 0. 0. 0.]


In [37]:
var_row = var(A, ddof=1, axis = 1)

In [38]:
print(var_row)

[3.5 3.5]


In [40]:
# standard Deviation 

In [41]:
from numpy import std

In [42]:
col_std = std(A, ddof=1, axis = 0)

In [43]:
print(col_std)

[0. 0. 0. 0. 0. 0.]


In [44]:
row_std = std(A, ddof=1, axis = 1)

In [45]:
print(row_std)

[1.87082869 1.87082869]
