In [11]:
from numpy import array
from numpy import cov
from numpy import std

In [12]:
x = array([1,2,3,4,5,6])
y = array([6,5,4,3,2,1])

In [13]:
Sigma = cov(x,y)[0,1]

In [14]:
print(Sigma)

-3.5


In [21]:
#pearson correlation coeffcient

In [22]:
# Sigma / std(x)* std(y)

In [25]:
corr = Sigma/(std(x, ddof=1)*std(y, ddof=1))

In [26]:
print(corr)

-1.0


In [27]:
# complete function in numpy as

In [28]:
from numpy import corrcoef

In [31]:
corr = corrcoef(x,y)[0][1]

In [32]:
print(corr)

-1.0


In [33]:
# Covariance Matrix

In [34]:
X = array([ [1, 5, 8], [3, 5, 11], [2, 4, 9], [3, 6, 10], [1, 5, 10]]) 

In [35]:
print(X)

[[ 1  5  8]
 [ 3  5 11]
 [ 2  4  9]
 [ 3  6 10]
 [ 1  5 10]]


In [36]:
cov_mat = cov(X.T)

In [37]:
print(cov_mat)

[[1.   0.25 0.75]
 [0.25 0.5  0.25]
 [0.75 0.25 1.3 ]]
